version: '3.8'
services:
  playwright-app:
    build:
      context: .
    container_name: playwright-jlesage
    ports:
      - "5801:5801"
      - "5800:5800"
    volumes:
      - playwright-data:/data
    shm_size: "2gb"

volumes:
  playwright-data: