version: '3.8'
services:
  playwright-app:
    build:
      context: .
    container_name: playwright-jlesage
    environment:
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - VNC_PASSWORD=password
    #   USER_ID: "0"
    #   GROUP_ID: "0"
    ports:
      - "5800:5800"
      - "5801:5801"
      - "5802:5802"
      - "9222:9222"
      - "9223:9223"
    volumes:
      - playwright-data:/data
    shm_size: "2gb"

volumes:
  playwright-data: